version: '3.8'

services:
  app:
    build: .
    container_name: taskmanager_app
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/taskmanager
      - JWT_SECRET=default_secret
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - .:/app
    command: ["sh", "./entrypoint.sh"]

  db:
    image: mysql:8.0
    container_name: taskmanager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanager
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
