version: '3'
services:
  app:
    build: .
    container_name: taskmanager-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://root:root@172.17.0.1:3306/taskmanager"
    volumes:
      - ./:/app
      - /app/node_modules
